# Generated by Django 6.0.6 on 2026-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecomponent',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancecomponent',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancecomponent',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
