# Generated by Django 6.0.4 on 2026-06-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_sessions', to='backend.building'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='maintenance_sessions', to='backend.equipment'),
        ),
    ]
