# Generated by Django 6.0.6 on 2026-06-13 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_maintenance_building_maintenance_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='attachments_note',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='is_janitorial',
        ),
    ]
