# Generated by Django 6.0.4 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_maintenancerecord_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
