# Generated by Django 6.0.6 on 2026-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_building_building_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_id',
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
