# Generated by Django 6.0.6 on 2026-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_equipmentcomponentpreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="component_preset",
            field=models.ManyToManyField(
                blank=True,
                related_name="equipment",
                to="backend.equipmentcomponentpreset",
            ),
        ),
    ]
