# Generated by Django 6.0.6 on 2026-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_remove_building_building_id_alter_building_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="qr_code",
            field=models.CharField(blank=True, default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
