# Generated by Django 6.0.6 on 2026-06-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_equipment_component_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="year_of_establishment",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
