# Generated by Django 5.2.4 on 2026-06-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_backendmenu_id_alter_building_id_and_more"),
        ("backend", "0005_alter_equipment_qr_code"),
    ]

    operations = []
