# Generated by Django 6.0.6 on 2026-06-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_building_year_of_establishment"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="installment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
