# Generated by Django 6.0.6 on 2026-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_equipment_installment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancecomponent',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
