# Generated by Django 6.0.6 on 2026-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_backendmenu_id_alter_building_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='nickname',
        ),
        migrations.AddField(
            model_name='building',
            name='building_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='building',
            name='surname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
