# Generated by Django 6.0.6 on 2026-06-11 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_remove_building_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketactivitylog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
