# Generated by Django 6.0.6 on 2026-06-11 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_ticketactivitylog_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="technician",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="technician",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="technician",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="technician",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
