# Generated by Django 6.0.6 on 2026-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_technician_email_technician_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigntechnician",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tickets",
                to="backend.technician",
            ),
        ),
    ]
